name: simplecmp-service-db
type: php
docroot: public
php_version: "8.3"
database:
  type: sqlite
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
hooks:
  post-start:
    - exec: "composer install --no-dev --quiet"
omit_containers:
  - db
  - dba
