/**
 * Consent-Log types — Phase 2 audit trail.
 *
 * The companion {@link ConsentLogger} watches a {@link ConsentManager}
 * and POSTs each confirmed decision to a host-side endpoint
 * (currently TYPO3 `/api/simplecmp/v1/consent-log`), bound to the
 * snapshot `version_hash` of the banner state that was active at
 * decision time.
 *
 * Visitor pseudonymization happens server-side: the raw `visitorUuid`
 * is sent in the POST body and the host computes
 * `HMAC-SHA256(uuid, bridge_secret || ':' || source)` before storing.
 * The raw UUID is persisted only in the visitor's own `localStorage`
 * under a separate key — never in the host's DB.
 *
 * @see docs/cms-bridge-webhook.md for the sister `cmsBridgeUrl` shape.
 */

import type { CmsBridgeAuth } from '../cms-bridge/types.js';

/**
 * Public init-config slot. Host emits this when the operator opted in
 * via the host's equivalent of `simplecmp.consentLogUrl`. Receiving
 * config: `SimpleCMP.init({..., consentLog: {...}})`.
 */
export interface ConsentLogConfig {
  /** Endpoint URL the logger POSTs decisions to. Required. */
  url: string;
  /**
   * Optional source identifier — defaults to {@link SimpleCMPConfig.storageName}
   * or `'default'`. Matches the host's `bridgeSource()` derivation so
   * nonces issued for the bridge auto-work for the consent-log.
   */
  source?: string;
  /**
   * Bearer-token auth, shape-compatible with `CmsBridgeAuth`. When
   * `refreshUrl` is set, the logger fetches a fresh token on 401 and
   * retries the POST once — same REQ-N9 mechanism the bridge uses,
   * including in-flight dedup.
   */
  auth?: CmsBridgeAuth;
  /**
   * Snapshot `version_hash` (sha256 hex, 64 chars) of the banner
   * state active at page-load time. The host stamps it in here so
   * each posted decision can later be reconciled against the
   * snapshot the visitor was looking at.
   */
  configVersion?: string;
}

/** ConsentLogger construction options. */
export interface ConsentLogOptions extends ConsentLogConfig {
  /** Stable per-visitor UUID v4. Generated by {@link getOrCreateVisitorUuid}. */
  visitorUuid: string;
  /** Override `globalThis.fetch`. Tests inject; runtime uses the global. */
  fetch?: typeof fetch;
  /** Network timeout per POST, in ms. Default `5000`. */
  timeoutMs?: number;
  /**
   * Tests pass a stub navigator; runtime uses `globalThis.navigator`.
   * Used only to derive `uaFamily` (coarse browser bucket).
   */
  navigator?: Pick<Navigator, 'userAgent'> | undefined;
  /**
   * Tests pass a stub location; runtime uses `globalThis.location`.
   * Used only to derive `pageHost` (hostname only, never path/query).
   */
  location?: Pick<Location, 'hostname'> | undefined;
}

/**
 * POST body shape — Schema v1. The host validates this against
 * `ConsentLogPayloadValidator` in TYPO3.
 */
export interface ConsentLogPayload {
  schemaVersion: 1;
  source: string;
  versionHash: string;
  visitorUuid: string;
  decisions: Record<string, boolean>;
  decisionType: 'accept' | 'decline' | 'script' | 'partial';
  pageHost?: string;
  uaFamily?: 'chrome' | 'firefox' | 'safari' | 'edge' | 'opera' | 'other';
}

/**
 * Notification payload emitted by `ConsentManager.notify('saveConsents', …)`.
 * Mirrors the runtime shape; defined here so we don't depend on the
 * engine's internal type aliasing.
 */
export interface SaveConsentsNotification {
  changes: Record<string, boolean>;
  consents: Record<string, boolean>;
  type: string;
}
